name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            platform: linux
            arch: x64
            asset_name: ssh-commander-linux-x64
            build_deb: true
          - os: ubuntu-20.04
            platform: linux
            arch: arm64
            asset_name: ssh-commander-linux-arm64
          - os: macos-latest
            platform: macos
            arch: x64
            asset_name: ssh-commander-macos-x64
          - os: macos-14
            platform: macos
            arch: arm64
            asset_name: ssh-commander-macos-arm64
          - os: windows-latest
            platform: windows
            arch: x64
            asset_name: ssh-commander-windows-x64

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        if [ "${{ matrix.platform }}" = "windows" ]; then
          pyinstaller --onefile --noupx --name ${{ matrix.asset_name }} \
            --exclude-module _bootlocale \
            --exclude-module PIL \
            --exclude-module numpy \
            --exclude-module pandas \
            --exclude-module matplotlib \
            --exclude-module tkinter \
            --exclude-module unittest \
            --exclude-module email \
            --exclude-module http \
            --exclude-module html \
            --exclude-module xml \
            --exclude-module pydoc \
            ssh_commander.py
        else
          pyinstaller --onefile --noupx --name ${{ matrix.asset_name }} \
            --exclude-module _bootlocale \
            --exclude-module PIL \
            --exclude-module numpy \
            --exclude-module pandas \
            --exclude-module matplotlib \
            --exclude-module tkinter \
            --exclude-module unittest \
            --exclude-module email \
            --exclude-module http \
            --exclude-module html \
            --exclude-module xml \
            --exclude-module pydoc \
            ssh_commander.py
        fi
      shell: bash
        
    - name: Package Release (Unix)
      if: matrix.platform != 'windows'
      run: |
        # Create a clean directory for the release
        rm -rf release ssh-commander
        mkdir -p release
        
        # Create the package directory with correct name
        mkdir -p ssh-commander
        cp dist/${{ matrix.asset_name }} ssh-commander/
        cp servers.yaml.example ssh-commander/
        cp README.md ssh-commander/
        cp install.sh ssh-commander/
        
        # Create the archive
        tar -czf release/${{ matrix.asset_name }}.tar.gz ssh-commander
        
        # Cleanup
        rm -rf ssh-commander
      shell: bash

    - name: Package Release (Windows)
      if: matrix.platform == 'windows'
      shell: pwsh
      run: |
        # Clean up and create directories
        Remove-Item -Path release -Recurse -Force -ErrorAction SilentlyContinue
        New-Item -ItemType Directory -Force -Path release
        
        # Create package directory
        New-Item -ItemType Directory -Force -Path ssh-commander
        Copy-Item dist/${{ matrix.asset_name }}.exe ssh-commander/
        Copy-Item servers.yaml.example ssh-commander/
        Copy-Item README.md ssh-commander/
        Copy-Item install.ps1 ssh-commander/
        
        # Create archive
        Compress-Archive -Path ssh-commander -DestinationPath release/${{ matrix.asset_name }}.zip
        
        # Cleanup
        Remove-Item -Path ssh-commander -Recurse -Force

    - name: Build Debian Package
      if: matrix.build_deb
      run: |
        # Install build dependencies
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper dh-python python3-all python3-setuptools python3-pip python3-paramiko python3-yaml python3-colorama
        
        # Fix pip permissions
        sudo chown -R $USER:$USER ~/.cache/pip
        
        # Extract version from git tag
        VERSION=${GITHUB_REF_NAME#v}
        NOW=$(date -R)
        
        # Create changelog
        printf 'ssh-commander (%s) unstable; urgency=medium\n\n  * Release version %s\n\n -- GitHub Actions <actions@github.com>  %s\n' "$VERSION" "$VERSION" "$NOW" > debian/changelog
        
        # Build the package
        dpkg-buildpackage -us -uc -b
        
        # Copy the .deb file to release directory and generate checksum
        cp ../ssh-commander_*.deb release/
        cd release
        sha256sum ssh-commander_*.deb > ssh-commander_${VERSION}_amd64.deb.sha256
        cd ..

    - name: Generate SHA256 checksums (Unix)
      if: matrix.platform != 'windows'
      run: |
        cd release
        if [ "$(uname)" = "Darwin" ]; then
          CHECKSUM_CMD="shasum -a 256"
        else
          CHECKSUM_CMD="sha256sum"
        fi
        $CHECKSUM_CMD ${{ matrix.asset_name }}.tar.gz > ${{ matrix.asset_name }}.tar.gz.sha256
      shell: bash

    - name: Generate SHA256 checksums (Windows)
      if: matrix.platform == 'windows'
      shell: pwsh
      run: |
        cd release
        $hash = Get-FileHash -Algorithm SHA256 ${{ matrix.asset_name }}.zip
        "$($hash.Hash)  ${{ matrix.asset_name }}.zip" | Out-File -Encoding UTF8 ${{ matrix.asset_name }}.zip.sha256

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}-artifacts
        path: |
          release/*.tar.gz
          release/*.zip
          release/*.sha256
          release/*.deb
        if-no-files-found: error

  create-release:
    needs: build
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
          
      - name: Create Release Notes
        run: |
          echo "# SSH Commander ${GITHUB_REF_NAME}" > release_notes.md
          echo "" >> release_notes.md
          echo "## Installation" >> release_notes.md
          echo "" >> release_notes.md
          echo "1. Download the appropriate archive for your platform:" >> release_notes.md
          echo "   - macOS ARM64: \`ssh-commander-macos-arm64.tar.gz\`" >> release_notes.md
          echo "   - macOS x64: \`ssh-commander-macos-x64.tar.gz\`" >> release_notes.md
          echo "   - Linux x64: \`ssh-commander-linux-x64.tar.gz\`" >> release_notes.md
          echo "   - Linux ARM64: \`ssh-commander-linux-arm64.tar.gz\`" >> release_notes.md
          echo "   - Windows x64: \`ssh-commander-windows-x64.zip\`" >> release_notes.md
          echo "" >> release_notes.md
          echo "2. Extract the archive" >> release_notes.md
          echo "3. Run the installation script:" >> release_notes.md
          echo "   For macOS/Linux:" >> release_notes.md
          echo "   \`\`\`bash" >> release_notes.md
          echo "   sudo ./install.sh" >> release_notes.md
          echo "   \`\`\`" >> release_notes.md
          echo "" >> release_notes.md
          echo "   For Windows (Run PowerShell as Administrator):" >> release_notes.md
          echo "   \`\`\`powershell" >> release_notes.md
          echo "   .\install.ps1" >> release_notes.md
          echo "   \`\`\`" >> release_notes.md
          echo "" >> release_notes.md
          echo "## SHA256 Checksums" >> release_notes.md
          echo "\`\`\`" >> release_notes.md
          cat artifacts/*.sha256 >> release_notes.md
          echo "\`\`\`" >> release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*.tar.gz
            artifacts/*.zip
            artifacts/*.sha256
            artifacts/*.deb
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
